matrix:
  include:
    - language: ruby
      rvm:
        - 2.3
        - 2.2
        - jruby

      before_install:
        - cd practicals

      install:
        - make install
        - make stylesheets

      script:
        - make html

    - language: node_js
      node_js:
        - "10"
        - "8"

      before_install:
        - cd slides

      install:
        - make install

      script:
        - make slides
