version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:2-10
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
