version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:2-10
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install asciidoctor, compass and revealmd
          command: make install
      - run:
          name: Generate html from markup text slides and coursework
          command: make html
