version: 2

jobs:
  build-and-deploy:
    branches:
      only:
        - master
    docker:
      - image: starefossen/ruby-node:2-10
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install asciidoctor, compass and revealmd
          command: make install
      - run:
          name: Generate html from markup text slides and coursework
          command: make html
      - run:
          name: Push subtree folder build to branch gh-pages on Github
          command: git subtree push --prefix build origin gh-pages

workflows:
  version: 2
  workflow:
    jobs:
      - build-and-deploy
